//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<int> CargoID { get; set; }
        public Nullable<int> ShippingID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Shipment Shipment { get; set; }
    }
}
