//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cargo()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int CargoID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<double> CargoWeight { get; set; }
        public Nullable<double> CargoHeight { get; set; }
        public Nullable<double> CargoWidth { get; set; }
        public Nullable<double> CargoLength { get; set; }
        public string CargoName { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
